import Head from 'next/head'
import Homepage from '../components/Homepage/Homepage'
import Login from '../components/Login/Login'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Homepage /> */}
      <Login/>
    </>
  )
}
